# Generated by Django 5.2.13 on 2026-04-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeRecord',
        ),
    ]
